dbApp/urls.py
from django.urls import path
from . import views

app_name = "dbApp"

urlpatterns = [
    path('', views.index, name="index"),
]

dbTest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dbApp.urls')),
    path('user/', include('users.urls')),
    path('user/', include("django.contrib.auth.urls")),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register, name="register"),
]

dbApp/models.py
from django.db import models

# Create your models here.

class Text(models.Model):
    user_name = models.CharField(max_length=250)
    input_text = models.CharField(max_length=250)

    def __str__(self):
        return self.user_name

users/models.py
from django.db import models

# Create your models here.

dbApp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from .models import Text

# Create your views here.

def getComments():
    returnList = []
    for comment in Text.objects.all():
        returnList.append([comment.user_name, comment.input_text])
    returnList.reverse()
    return returnList

def index(request):
    if request.method == "POST":
        # code to save comment in db
        if request.POST.get("comment"):
            comment = Text(user_name=request.user.username, input_text=request.POST.get("comment"))
            comment.save()
            return redirect(request.path)
        
    returnList = getComments()
    context = {"comments": returnList}
    return render(request, "dbApp/index.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/user/login")
    else:
        form = UserCreationForm()
    
    return render(request, "users/register.html", {"form": form})

dbApp/templates/dbApp/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>DB Test</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        {% if user.is_authenticated %}
            <h3>Logged in as {{ user.get_username }}</h3>
            <button type="button" class="btn btn-secondary" onclick="location.href = '/user/logout';">Logout</button>
            <div class="p-3">
                <form action="{% url 'dbApp:index' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group mb-2" >
                        <label for="comment" class="my-1">Comment</label>
                        <textarea class="form-control" type="text" name="comment" placeholder="Type comment"></textarea> 
                    </div>
                    <input type="submit" class="btn btn-light mt-2">
                </form>
            </div>   
        {% else %}
            <button type="button" class="btn btn-secondary" onclick="location.href = '/user/login';">Login</button>
            <p>You need to login to comment. Login <a href="/user/login">here</a></p>
        {% endif %}
         
        {% if comments %}
            {% for comment in comments %}
                <div class="card text-white bg-secondary mb-3 ms-3" style="max-width: 28rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{comment.0}}</h3>
                        <p class="card-text">{{comment.1}}</p>
                    </div>
                </div> 
            {% empty%}
                <h2>No comments found</h2>
            {% endfor %}
        {% endif %}
    </body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>Register</title>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% load crispy_forms_tags %}
        {% load crispy_forms_filters %}
    </head>
    <body>
        <h1 class="m-5">Create an account</h1>
        <form method="post" class="form-group m-5">
            {% csrf_token %}
            {{ form|crispy }}
            <p>Already have an account? Login <a href="/user/login">here</a></p>
            <button type="submit" class="btn btn-primary">Register</button>
          </form>
    </body>
</html>